# Generated by Django 5.2.3 on 2025-07-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='code_file_uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
